### PR TITLE
Multiple parties in progress

### PR DESCRIPTION
**Pull request by BryceStevenWilley**
This change will let the interview support multiple parties, editing those parties after the initial section, and can handle their attorneys slightly better too.

Some general coding practices I used that might help in the future:
* `len(users)`, etc. instead of referring directly to `target_number`; target number won't be accurate anymore if someone adds or removes parties on the review screen.
* On the form, it's simpler to refer to `plaintiffs_attorney`, but when during the interview, it's simpler to refer to `other_parties` attorney. I made those changes, which simplifies how we can ask for and edit the other party's attorney
* I added `users.revisit` and `users.table` for `users`, `other_parties`, and `other_party_attorneys` (Those should be upstream, I might eventually make a change there).

Things that we'd need to verify:
* how to handle attorneys, and if we can put more than one on the form.  I don't think other jurisdictions had a good solution to handling multiple attorneys, etc. I'm not sure where they would go on the form, so it might not be possible at the moment.

This PR ended up being bigger than I thought it would; I can try to separate out some of these changes into different PRs if that would help (so it's fewer things changing at a time). But it'll still be a fairly large change I think. Happy to hop on a call and walk through it, making sure I didn't miss anything.

### CODE REVIEW

**Comment by ekressmiller** [comment]
Thank you Bryce! I'm talking with the other lawyers about whether we can just move additional parties and their attorneys to an addendum.  

FYI, I get about 2 days a week of my work time to devote to Docassemble stuff, so there may be days where I'm not immediately looking at what you send. If there's ever something where you're stuck until I reply or something is more urgent, please feel free to send an email or a chat to let me know!

**Comment by ekressmiller** [comment]
After talking with the other lawyers, I do think we're fine to just put the info for the first party on each side (and their lawyer, if any), in the boxes on the front of the form, then send any additional parties and lawyers to an addendum. If there are multiple parties, we'll need to ask which one is the "first party" because that's the one we should list on the front of the form, even if it's not the user.  Does that cover the issue you pointed out about multiple attorneys?

I've been looking over the code, thank you so much! I think a call would be good, mostly because I think it'd help me internalize some of what you've done for the future. I'm totally free tomorrow Tuesday if there'd be a good time for you.

**Comment by BryceStevenWilley** [comment]
Okay, multiple attorneys are in! Here are some photos of what the motion header blocks and addendum look like now:

Screenshot from 2023-10-10 11-38-54


Screenshot from 2023-10-10 11-39-03

A last few questions that we should discuss:

* do attorneys need to be explicitly associated with parties? (this used to be asked by `other_side_share_lawyer`, but the way it was used doesn't make sense anymore)
    * if so, can parties have more than one attorney?

**Comment by ekressmiller** [comment]
Hey Bryce, awesome, thank you!

We do want to know if a lawyer is associated with a particular party.  _I think_ ideally the addendum might look something like this for a self-represented party vs. a party with a lawyer:

**Additional plaintiffs:**
-John II Plaintiff  (self-represented)
--123 John street, Johnville MI 48328
--(111) 234-2343

-Suzy III Plaintiff
--**Lawyer**: Hannah McLawyer, P38243
---2343 Lawyer street, Lawyerville MI 32432
---(342) 234-23433

I am checking with Kim (who's in charge of this tool) to make sure we're good to only collect and print out party address/phone info if the party is self-represented. (There was a recent wrinkle added about that.)

A lawyer could sometimes represent multiple parties. I think for our purposes, it'd be fine to just repeat the lawyer information with each of the lawyer's clients, even though it's redundant. I really don't expect this situation to arise very often.

A person could theoretically have more than one lawyer--let me check with Kim on how to handle that too.

**Comment by ekressmiller** [comment]
Bryce, I think you should pause any more work on this for the moment, Kim and I are getting turned around with the court rules, and we should get to solid ground on that before investing more time in the exact shape of what we do with the parties and lawyers. 

(Sorry, I thought we were already on solid ground or I would have stopped you sooner!)

**Comment by ekressmiller** [comment]
@BryceStevenWilley After much back and forth with Kim and the other lawyers, here is the verdict:

1) We just need to list the _first party_ (i.e. the party that is listed first in the complaint or other case-initiating doc) for each side in the caption (with contact/attorney info). 

2) We _do_ need to know if there is more than one party on each side, because we will add "et al" after the first party name if so. 

3) We still need the user's name, _but_ we only need their phone and address if they are the first party on their side. We can still assume the user has no lawyer.  

Sorry again for not figuring this out until after you worked on the program! I thought I had figured it out but clearly hadn't asked enough questions.

Given this, do you have thoughts about how you'd like to proceed? If you could edit this pull request to only contain changes that are still relevant in light of the new goalposts, I could take another crack at it from that point. But if you feel like you're on a roll and want to work on this version that could also work.

**Comment by BryceStevenWilley** [comment]
Awesome! This PR does all of those 3 things already (it said "MORE IN ATTACHMENT" instead of "et al.", but that's a straightforward fix), so that's good.

There are some implicit things that I want to confirm:

* do the names of the parties other than the first party on each side go in the attachment, or do we not need any information about additional parties, just that they exist?
* for lawyers on the other side, should we assume there's only one Lawyer who's information we need to collect?

**Comment by ekressmiller** [comment]
1) We just need to know that other parties exist. We don't need to to list any info about parties except the first party on each side and, if the user is not the first party on either side, the user's name.
2) We can assume each party has at most one lawyer.  The first party on each side could have a lawyer (except when the first party on one side is the user).

**Comment by BryceStevenWilley** [comment]
I moved over the easier changes that we can get in into #22.

I ran into a few problems when trying to simplify things to how you mentioned; writing down my notes in case it's helpful to you if you get to take a shot at it:

* the main problem is that all of the AssemblyLine assumes that `users[0]` is "you", the person filling in the form. If `users[0]` can't be that (since we only want the first party listed on the form).
    * do we still gather the user's information if only the first party is going on the form? Where does the user's name go? (I assume that the moving party should be present)
* If we only keep around 1 party from each side, we can't use the simpler ways that docassemble handles parties, like `users.gather()`, the review tables, etc, since they all assume that some information is present about these other parties. We have to handle everything as either a single Individual (not a list), with an extra question about if there are more parties. The review part in particular is difficult, since we'll have to re-evaluate the object itself instead of letting people add and remove parties.

**Comment by ekressmiller** [comment]
Thank you Bryce! I hope your wedding and honeymoon are wonderful!

**Comment by ekressmiller** [comment]
Note to future self, ran into some problems using "len()" in the attachment block. Michelle suggested using _variable_.number_gathered() instead and it seemed to resolve the issues.

**Comment by BryceStevenWilley** [comment]
Going to close this PR, should be covered by #28

**Pull request closed without merging**
